use anyhow::{Context, Result};
use clap::Parser;
use patcher::{
    graphics::{
        TILE_CANONICALIZATION_REVISION, TileFingerprintIndex, TileFingerprintSheet,
        canonicalize_tile,
    },
    import::Importer,
    verify_vanilla_rom,
};
use sha2::{Digest, Sha256};
use std::{collections::BTreeSet, fmt::Write, fs, path::PathBuf};

#[derive(Parser)]
#[command(about = "Build SHA-256 fingerprints for vanilla background graphics sheets $00-$60")]
struct Args {
    input_rom: PathBuf,
    output_index: PathBuf,
}

fn main() -> Result<()> {
    let args = Args::parse();
    let rom = fs::read(&args.input_rom)
        .with_context(|| format!("failed to read {}", args.input_rom.display()))?;
    let mut rom_sha256 = String::with_capacity(64);
    for byte in verify_vanilla_rom(&rom)? {
        write!(rom_sha256, "{byte:02x}")?;
    }
    let importer = Importer::new(rom)?;
    let mut index = TileFingerprintIndex {
        canonicalization_revision: TILE_CANONICALIZATION_REVISION,
        rom_sha256,
        notes: vec![
            "This file is auto-generated by crates/build_tile_fingerprints/src/main.rs. Do not edit it.".to_owned(),
            "These are SHA-256 hashes of canonicalized graphics tiles from the vanilla game.".to_owned(),
            "The retiling catalog builder uses these fingerprints to reference matching vanilla graphics without including copied vanilla tile pixels in the catalog.".to_owned(),
            "This design is intended to avoid potential copyright liability while allowing the catalog to be built without a vanilla ROM.".to_owned(),
        ],
        sheets: Vec::new(),
    };
    let mut tile_count = 0;
    let mut unique_fingerprints = BTreeSet::new();
    for sheet in 0..=0x60 {
        let tiles = importer.read_background_graphics_sheet(sheet)?;
        let mut fingerprints = Vec::with_capacity(tiles.len());
        for tile in tiles {
            let canonical = canonicalize_tile(&tile);
            let mut fingerprint = String::with_capacity(64);
            for byte in Sha256::digest(canonical.pixels) {
                write!(fingerprint, "{byte:02x}")?;
            }
            unique_fingerprints.insert(fingerprint.clone());
            fingerprints.push(fingerprint);
            tile_count += 1;
        }
        index.sheets.push(TileFingerprintSheet {
            sheet,
            tile_fingerprints: fingerprints,
        });
    }

    let mut json = serde_json::to_string_pretty(&index)?;
    json.push('\n');
    fs::write(&args.output_index, &json)
        .with_context(|| format!("failed to write {}", args.output_index.display()))?;
    eprintln!(
        "{}: {} sheets, {tile_count} tiles, {} unique fingerprints, {} bytes",
        args.output_index.display(),
        index.sheets.len(),
        unique_fingerprints.len(),
        json.len(),
    );
    Ok(())
}
